import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : value === 'ko' ? 'ko' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    generateShareImage: '分享',
    generatingShareImage: '生成中...',
    shareImageReadyToShare: '再次点击分享',
    shareImageReady: '已生成',
    shareImageFailed: '重试',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
    priceChart: 'K 线走势',
    priceChartLoading: '加载行情中...',
    priceChartFailed: '行情加载失败',
    noPriceData: '暂无行情数据',
    navMetrics: '净值指标',
    unitNav: '单位净值',
    riskGrade: '风险等级',
    return1m: '近1月',
    return3m: '近3月',
    return6m: '近6月',
    return1y: '近1年',
    maxDrawdown: '最大回撤',
    annualVolatility: '年化波动',
    sharpe: '夏普比率',
    insufficientData: '数据不足',
    fundDisclaimer: '不构成投资建议',
    riskHigh: '高',
    riskMedium: '中',
    riskLow: '低',
    assetAllocation: '资产配置',
    reportDate: '报告期',
    topHoldings: '十大重仓股',
    category: '类别',
    percentOfNav: '占净值比例',
    holdingsRank: '排名',
    holdingsStock: '股票',
    shareCount: '持股(万股)',
    marketValue: '市值(万元)',
    assetStock: '股票',
    assetBond: '债券',
    assetCash: '现金',
    netAsset: '净资产',
    oneHundredMillion: '亿元',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    generateShareImage: 'Share',
    generatingShareImage: 'Preparing...',
    shareImageReadyToShare: 'Share now',
    shareImageReady: 'Ready',
    shareImageFailed: 'Retry',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
    priceChart: 'PRICE CHART',
    priceChartLoading: 'Loading price data...',
    priceChartFailed: 'Failed to load price data',
    noPriceData: 'No price data',
    navMetrics: 'NAV Metrics',
    unitNav: 'Unit NAV',
    riskGrade: 'Risk Grade',
    return1m: '1M',
    return3m: '3M',
    return6m: '6M',
    return1y: '1Y',
    maxDrawdown: 'Max Drawdown',
    annualVolatility: 'Annual Volatility',
    sharpe: 'Sharpe Ratio',
    insufficientData: 'Insufficient data',
    fundDisclaimer: 'Not investment advice',
    riskHigh: 'High',
    riskMedium: 'Medium',
    riskLow: 'Low',
    assetAllocation: 'Asset Allocation',
    reportDate: 'Report Date',
    topHoldings: 'Top Holdings',
    category: 'Category',
    percentOfNav: '% of NAV',
    holdingsRank: 'Rank',
    holdingsStock: 'Stock',
    shareCount: 'Shares (10k)',
    marketValue: 'MV (10k yuan)',
    assetStock: 'Stocks',
    assetBond: 'Bonds',
    assetCash: 'Cash',
    netAsset: 'Net Assets',
    oneHundredMillion: '100M',
  },
  ko: {
    keyInsights: '핵심 인사이트',
    noAnalysisSummary: '분석 결론 없음',
    actionAdvice: '대응 전략',
    noAdvice: '제안 없음',
    trendPrediction: '추세 전망',
    noPrediction: '예측 없음',
    marketSentiment: '시장 심리',
    strategyPoints: '전략 가격대',
    sniperLevels: '대응 가격대',
    idealBuy: '이상적 매수가',
    secondaryBuy: '추가 매수가',
    stopLoss: '손절가',
    takeProfit: '목표가',
    noValue: '—',
    newsFeed: '뉴스 피드',
    relatedNews: '관련 뉴스',
    refresh: '새로고침',
    retry: '다시 시도',
    dismiss: '닫기',
    details: '상세 보기',
    loadingNews: '뉴스 불러오는 중...',
    noNews: '관련 뉴스 없음',
    noNewsDescription: '잠시 후 새로고침하여 최신 소식을 확인하세요.',
    transparency: '투명성',
    traceability: '데이터 추적',
    rawResult: '원본 분석 결과',
    analysisSnapshot: '분석 스냅샷',
    copy: '복사',
    copied: '복사됨!',
    recordId: '레코드 ID',
    fullReport: '전체 분석 리포트',
    loadingReport: '리포트 불러오는 중...',
    loadReportFailed: '리포트 불러오기 실패',
    copyMarkdownSource: 'Markdown 소스 복사',
    copyPlainText: '일반 텍스트 복사',
    generateShareImage: '공유',
    generatingShareImage: '생성 중...',
    shareImageReadyToShare: '지금 공유',
    shareImageReady: '완료',
    shareImageFailed: '다시 시도',
    analysisModel: '분석 모델',
    fearGreedIndex: '공포·탐욕 지수',
    boardLinkage: '섹터 연동',
    relatedBoards: '관련 섹터',
    leadingBoard: '강세',
    laggingBoard: '약세',
    neutralBoard: '중립',
    reanalyze: '재분석',
    priceChart: '주가 차트',
    priceChartLoading: '시세 불러오는 중...',
    priceChartFailed: '시세 불러오기 실패',
    noPriceData: '시세 데이터 없음',
    navMetrics: 'NAV 지표',
    unitNav: '단위 NAV',
    riskGrade: '위험 등급',
    return1m: '1개월',
    return3m: '3개월',
    return6m: '6개월',
    return1y: '1년',
    maxDrawdown: '최대 낙폭',
    annualVolatility: '연환산 변동성',
    sharpe: '샤프 비율',
    insufficientData: '데이터 부족',
    fundDisclaimer: '투자 권유 아님',
    riskHigh: '높음',
    riskMedium: '중간',
    riskLow: '낮음',
    assetAllocation: '자산 배분',
    reportDate: '보고 기간',
    topHoldings: '상위 보유종목',
    category: '구분',
    percentOfNav: 'NAV 비중',
    holdingsRank: '순위',
    holdingsStock: '종목',
    shareCount: '보유량(만주)',
    marketValue: '시가총액(만원)',
    assetStock: '주식',
    assetBond: '채권',
    assetCash: '현금',
    netAsset: '순자산',
    oneHundredMillion: '억원',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
